version: "3.3"
services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: api:dev
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: CacaoSV
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: CacaoSV
      