version: 2
jobs:
  linux:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: CacaoSV
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
    steps:
      - run:
          name: Building 
          command: swift build
      - run:
          name: Testing
          command: swift test

workflows:
  version: 2
  build-linux:
    jobs:
      - linux
