version: 2
jobs:
  linux:
    docker:
      - image: swift:4.1
        environment:
        TEST_POSTGRES_PASSWORD: ""
        TEST_POSTGRES_USER: postgres
        TEST_POSTGRES_HOST: 127.0.0.1
        TEST_POSTGRES_PORT: 5432
        TEST_POSTGRES_DATABASE: CacaoSVTest
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Checking files 
          command: ls
      - run:
          name: Building 
          command: swift build
      - run:
          name: Testing
          command: swift test

workflows:
  version: 2
  build-linux:
    jobs:
      - linux

